# Generated by Django 4.2.7 on 2025-12-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-confidence', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
        migrations.AddField(
            model_name='claim',
            name='has_qualifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_negated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='contradiction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='contradiction_type',
            field=models.CharField(choices=[('direct_negation', 'Direct Negation'), ('semantic', 'Semantic Conflict'), ('statistical', 'Statistical Discrepancy'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source'),
        ),
        migrations.AlterField(
            model_name='content',
            name='trust_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='contradiction',
            name='claim_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contradictions_as_a', to='core.claim'),
        ),
        migrations.AlterField(
            model_name='contradiction',
            name='claim_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contradictions_as_b', to='core.claim'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='contradiction',
            unique_together={('claim_a', 'claim_b')},
        ),
        migrations.RemoveField(
            model_name='contradiction',
            name='content',
        ),
    ]
