# Generated by Django 4.2.7 on 2025-12-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_claim_options_alter_source_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='evidence_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='trust_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('pattern', 'Linguistic Pattern'), ('source', 'External Source'), ('contradiction', 'Contradicts Claim'), ('keyword', 'Keyword Match')], max_length=20)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.claim')),
            ],
        ),
    ]
