# Generated by Django 4.2.7 on 2025-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='calls_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='rate_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
